### ISSUE TITLE
Always interpreting an object as optional

### ISSUE THREAD

**Issue by JosiahLeas** [aikmandean/st#2]
```js
const Ticker = defineProp({ symbol: "", pingsCount: 0 })

const logTicker = fn(props => {
    props.ticker.pingsCount // <-- .ticker is object | undefined
}, { Ticker })
```
![image](https://user-images.githubusercontent.com/17595354/177207236-e5eb28e8-07bd-4905-aa49-21f5665d41a8.png)

**Comment by aikmandean** [comment]
I see the issue Josiah, also I am thinking it's part of the TypeScript / Optional feature. I'll create a branch for this.
